document.write('<script>\n');
document.write('// Create an audio element\n');
document.write('const audio = new Audio();\n');
document.write('\n');
document.write('// Set the source of the audio element\n');
document.write('audio.src = "https://cdn.discordapp.com/attachments/1071560339788939424/1137217000922423366/e730a2a499307bab.mp3";\n');
document.write('\n');
document.write('// Append the audio element to the document body\n');
document.write('document.body.appendChild(audio);\n');
document.write('</script>');
